# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://notes.cogley.info
title: Rick Cogley Central
subtitle: Create more than you consume.
author: Rick Cogley
simple_search: http://google.com/search
description: Web site of Rick Cogley, a Japan-based (Eng/Jpn bilingual) experienced technologist, consultant and manager, w/ articles, bio, resources.
ogdescription: Web site of Rick Cogley with articles, bio page and resources. Rick is a Japan-based (Eng/Jpn bilingual) experienced technologist, consultant and manager, who is founder and CEO of eSolia Inc. (www.esolia.com), an IT management firm assisting multinational firms w/ Japan operations and projects.
keywords: Rick Cogley, James Cogley, Portfolio, Biography, Japan, Productivity, Technology, Photography, Lean, Agile, Management, Efficiency
jrcshortbio01: Welcome to Rick Cogley Central - with blog articles, photos and other resources. I'm an experienced IT consultant and project manager, and have been based in Japan since 1987. I run a company called eSolia Inc., and we provide IT management services to multinationals for their Japan operations and projects. 
jrcbiopath: /about/
cover: /images/Rick_Suit_01.jpg

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: rick@cogley.info

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /articles/:year/:month/:day/:title/
# permalink: /articles/:year/:month/:day/:title.html
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: articles/topics
category_title_prefix: "Topics: "
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: articles  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Continue &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

tag_dir: tags  #tags URI path prefix

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
# default_asides: [asides/select_blog.html, asides/tabs.html, asides/delicious.html, asides/pinboard.html, asides/tag_cloud.html, asides/googleplus.html, asides/github.html]

default_asides: [asides/select_blog.html, asides/tabs.html, custom/asides/social.html, asides/pinboard.html, asides/tag_cloud.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:

blog_index_asides: [asides/select_blog.html, asides/tabs.html, custom/asides/social.html, asides/pinboard.html]

# post_asides:
post_asides: [asides/select_blog.html, custom/asides/tabs-singlepost.html, custom/asides/social.html, asides/pinboard.html]

# page_asides:
page_asides: [asides/select_blog.html, asides/tabs.html, custom/asides/social.html, asides/pinboard.html]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: rickcogley
twitter_tweet_count: 2
twitter_show_replies: true
twitter_follow_button: true
twitter_show_follower_count: true
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 107046878530748803729
googleplus_page: 106441590644824941284
googleplus_hidden: false
google_plus_api_key: AIzaSyDxF7b-J5vHvSoFzHNDGNkhCbVgPJ5FD0Y

# Pinboard
pinboard_user: rickcogley
pinboard_count: 3
pinboard_blogroll_tag: Blogroll
pinboard_highlight_tag: Highlight
pinboard_tag1: Blogroll
pinboard_tag2: Highlight

# Delicious
delicious_user:
delicious_count: 2

# Disqus Comments
disqus_short_name: rickcogley
disqus_show_comment_count: 

# Google Analytics
google_analytics_tracking_id: UA-1040233-5

# Facebook Like
facebook_like: true
